### ISSUE TITLE
UTF-8 encoded strings are not interpreted

### ISSUE THREAD

**Issue by Hologos** [fidian/ansi#20]
Hi,

I finally migrated my dotfiles to `ansi` library. I am using `✔` as mark that my commits are being signed. Sadly, I am currently not able to print this mark using UTF-8 encoded syntax.

`ansi --bold --color=64 "\xE2\x9C\x94"` prints `\xE2\x9C\x94` instead of `✔`.

**Comment by fidian** [comment]
You don't just have a UTF-8 encoded string. Instead, you have a Unicode character encoded as UTF-8, then escaped as hex characters. You need to decode those hex characters. As proof, here's the same string passed to `echo`.

![image](https://user-images.githubusercontent.com/428348/69067998-a6482f80-09e9-11ea-8629-88b077916c73.png)

What you need to do is to convert the 12 characters of encoded hex into the 3 bytes of UTF-8. Once you have that part correct, the `ansi` command works just fine.

![image](https://user-images.githubusercontent.com/428348/69068065-c2e46780-09e9-11ea-93d5-e218fe092c0e.png)

So, the input to `ansi` needs to be the 3 UTF-8 encoded characters or the Unicode checkmark.

![image](https://user-images.githubusercontent.com/428348/69068118-d68fce00-09e9-11ea-8cd7-0a558f9429da.png)

You could also store this information as variables in your shell scripts. It would be faster than invoking `ansi` often. I learned this lesson with the Bash [maze game](https://github.com/fidian/maze) when profiling how long it took to draw the maze screens. If you only show the checkbox occasionally, the time drain is minimal. When doing color code generation hundreds of times you will want to optimize it by storing the color codes in a variable when possible.

![image](https://user-images.githubusercontent.com/428348/69068300-21a9e100-09ea-11ea-9445-0b0f4ab006c0.png)

I hope this clears up the problem you were experiencing.
