### ISSUE TITLE
There is not --reset-all option

### ISSUE THREAD

**Issue by Hologos** [fidian/ansi#22]
Hi,

in the README, there is an example of option `--reset` and its equivalent. `--reset-all` doesn't exist.
```
# Reset the terminal colors, reset to the default font, move the cursor
# to row 1 column 1, and show the cursor if it was previously hidden.
# This is the same as the --reset option.
ansi --erase-display=2 --reset-all --position=1,1 --show-cursor \
    --reset-font
```

```bash
$ ansi --reset-all test
--reset-all test
```

**Comment by fidian** [comment]
Yes, I missed that. I've updated the documentation to use `--reset-color` instead. Thanks for trying out the examples and reporting the problem!
