### ISSUE TITLE
Incorrect echos with `ansi::reportPosition` and the Linux console

### ISSUE THREAD

**Issue by adamsmd** [fidian/ansi#25]
Running `ansi::reportPosition` on a Linux console sometimes shows the escaped version of the report, as shown in the following example.

```bash
$ source s/ansi.git/ansi
$ ansi::reportPosition
3,1
$ ansi::reportPosition
\[[5;1R5,1
```

What I think is happening is that the report "\[[5;1R" is getting echoed when it shouldn't be.

Note that by "Linux console" I mean what you get with "Ctrl-Alt-F3", not a terminal emulator like `gnome-terminal`.

Also note that this is a very inconsistent bug.  Sometimes `ansi::reportPosition` behaves correctly, as in the first invocation above.  Sometimes, it behaves incorrectly, as in the second invocation above.  Thus, for testing, be sure to run `ansi::reportPosition` multiple times (e.g., run `for i in $(seq 1 100); do ansi::reportProblem; done)`, and even run it a few times).

## Proposed Solution

Using the `-p` option of `read` instead of `printf` seems to resolve this issue.  (I don't know why it resolves it, just that it does.)

Thus, the problem is fixed by changing the following lines https://github.com/fidian/ansi/blob/225a28e589a93f78820dbf921c8261aeea964676/ansi#L543-L547 to
```bash
    report=""
    # Note: `read` bypasses piping, which lets this work:
    # ansi --report-window-chars | cut -d , -f 1
    read -p "$ANSI_CSI""$1" -r -N "${#2}" -s -t 1 buff
```

(Sorry to not make a proper pull request of this fix.  I'm busy working on other things and just happened to notice this problem.)

**Comment by fidian** [comment]
Thanks! Your code fixes the problem when used on a console. I can confirm that it works fine for me as well and will be putting it into the codebase. I really appreciate the time you took to track down and suggest an alternative to correct the problem.
